CREATE DATABASE `gitlove`;
USE `gitlove`;

CREATE TABLE users (
`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(50) NOT NULL,
`username` VARCHAR(30) NOT NULL UNIQUE,
`email` VARCHAR(50) NOT NULL,
`password` VARCHAR(50) NOT NULL
);

CREATE TABLE repositories (
`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(50) NOT NULL,
`description` VARCHAR(100) NOT NULL,
`user` VARCHAR(30) NOT NULL,
`createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
INDEX `fk_user` (`user`),
CONSTRAINT `fk_user` FOREIGN KEY (`user`) REFERENCES `users` (`username`)
);